/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer;

import ControllerLayer.ExplotacionController;
import dto.ExplotacionDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class FrmExplotacion extends javax.swing.JFrame {

    /**
     * Creates new form FrmExplotacion
     */
    
    private final ExplotacionController explotacionController;
    public FrmExplotacion(ExplotacionController explotacionController) {
        initComponents();
        this.explotacionController = explotacionController;
        listarExplotacion();
    }
    
    private void listarExplotacion() {
        explotacionController.listarExplotacion(tbExplotacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdestado = new javax.swing.JTextField();
        txtCantidadacumulada = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbExplotacion = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdespecie = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbExplotacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Especie", "Id Estado", "Cantidad Explotada"
            }
        ));
        tbExplotacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbExplotacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbExplotacion);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Explotación");

        jLabel2.setText("Id Especie");

        jLabel3.setText("Id Estado");

        jLabel4.setText("Cantidad Explotada Acumulada");

        txtIdespecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdespecieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdestado, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtIdespecie)
                            .addComponent(txtCantidadacumulada))))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdespecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCantidadacumulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnRegresar))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbExplotacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbExplotacionMouseClicked
        int seleccion = tbExplotacion.rowAtPoint(evt.getPoint());
        try {
            
            System.out.println(Integer.parseInt((String)(tbExplotacion.getValueAt(seleccion, 0))));
            ExplotacionDTO ex = explotacionController.buscarExplotacion(Integer.parseInt((String)(tbExplotacion.getValueAt(seleccion, 0))));
            this.txtIdespecie.setText(String.valueOf(ex.getIdespecie()));
            this.txtIdestado.setText(String.valueOf(ex.getIdestado()));
            this.txtCantidadacumulada.setText(String.valueOf(ex.getCantidadacumulada()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO EXISTE LA EXPLOTACION SOLICITADA");
        }
    }//GEN-LAST:event_tbExplotacionMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int idespecie = 0;
        idespecie = Integer.parseInt(this.txtIdespecie.getText());

      
        ExplotacionDTO ex = explotacionController.buscarExplotacion(idespecie);

        if(ex.getIdespecie() != 0){
            this.txtIdespecie.setText(String.valueOf(ex.getIdespecie()));
            this.txtIdestado.setText(String.valueOf(ex.getIdestado()));
            this.txtCantidadacumulada.setText(String.valueOf(ex.getCantidadacumulada()));
        }
        else{
            JOptionPane.showMessageDialog(null, "No existe la explotacion");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FrmPrincipal frm = new FrmPrincipal();
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtIdespecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdespecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdespecieActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbExplotacion;
    private javax.swing.JTextField txtCantidadacumulada;
    private javax.swing.JTextField txtIdespecie;
    private javax.swing.JTextField txtIdestado;
    // End of variables declaration//GEN-END:variables
}
