/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer;

import ControllerLayer.EspecieController;
import dto.EspecieDTO;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class FrmEspecie extends javax.swing.JFrame {

   private final EspecieController especieController;
    
    public FrmEspecie(EspecieController especieController) {
        initComponents();
        this.especieController = especieController;
        listarEspecie();
        cargarComboIDHabitat();
        cargarComboIDCategoria();
    }
    
    public void listarEspecie(){
        especieController.listarEspecies(tbEspecie);
    }
    
    public void cargarComboIDHabitat(){
        especieController.llenarComboBoxHabitat(cboIDhabitatMod);
    }
    
    public void cargarComboIDCategoria(){
        especieController.llenarComboBoxCategoria(cboIDcategoriaMod);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdespecie = new javax.swing.JTextField();
        txtIdcategoria = new javax.swing.JTextField();
        txtIdhabitat = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEspecie = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        cboIDhabitatMod = new javax.swing.JComboBox<>();
        txtBuscarEspecie = new javax.swing.JTextField();
        txtNombreEspecieMod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboIDcategoriaMod = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Registro de Especies");

        jLabel2.setText("Id Especie");

        jLabel3.setText("Id Categoria");

        jLabel4.setText("Id Habitat");

        jLabel5.setText("Nombre");

        txtIdespecie.setEditable(false);

        txtIdcategoria.setEditable(false);

        txtIdhabitat.setEditable(false);

        txtNombre.setEditable(false);

        tbEspecie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Especie", "Id Categoria", "Id Habitat", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbEspecie.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tbEspecie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEspecieMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEspecie);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar por ID");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        cboIDhabitatMod.setToolTipText("");
        cboIDhabitatMod.setName(""); // NOI18N
        cboIDhabitatMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboIDhabitatModActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre");

        jLabel8.setText("Id Categoria");

        jLabel9.setText("Id Habitat");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("CRUD - ESPECIES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(51, 51, 51)
                            .addComponent(txtIdespecie, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(jLabel8)
                            .addGap(20, 20, 20)
                            .addComponent(txtIdcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(52, 52, 52)
                            .addComponent(txtIdhabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jLabel7)
                            .addGap(43, 43, 43)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnBuscar)
                            .addGap(53, 53, 53)
                            .addComponent(txtBuscarEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel5)
                            .addGap(53, 53, 53)
                            .addComponent(txtNombreEspecieMod, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel9)
                            .addGap(42, 42, 42)
                            .addComponent(cboIDhabitatMod, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel3)
                            .addGap(30, 30, 30)
                            .addComponent(cboIDcategoriaMod, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(txtIdespecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txtIdcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(txtIdhabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)
                        .addComponent(txtBuscarEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel5))
                        .addComponent(txtNombreEspecieMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnActualizar)
                            .addGap(7, 7, 7)
                            .addComponent(btnBorrar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(cboIDhabitatMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(cboIDcategoriaMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRegresar))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbEspecieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEspecieMouseClicked
        int seleccion = tbEspecie.rowAtPoint(evt.getPoint());
        try {
            
            System.out.println(Integer.parseInt((String)(tbEspecie.getValueAt(seleccion, 0))));
            EspecieDTO es = especieController.buscarEspecie(Integer.parseInt((String)(tbEspecie.getValueAt(seleccion, 0))));
            this.txtIdespecie.setText(String.valueOf(es.getIdespecie()));
            this.txtIdcategoria.setText(String.valueOf(es.getIdcategoria()));
            this.txtIdhabitat.setText(String.valueOf(es.getIdhabitat()));
            this.txtNombre.setText(String.valueOf(es.getNombre()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO EXISTE LA ESPECIE");
        }
    }//GEN-LAST:event_tbEspecieMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        EspecieDTO especie = new EspecieDTO();
        int idespecie = 0;
        int idcategoria = 0;
        int idhabitat = 0;
        String nombre = " ";

        String cadena1 = (String) cboIDhabitatMod.getSelectedItem();
        String[] partes1 = cadena1.split("-");
        String id_habitat = partes1[0];

        String cadena2 = (String) cboIDcategoriaMod.getSelectedItem();
        String[] partes2 = cadena2.split("-");
        String id_categoria = partes2[0];

        idespecie = Integer.valueOf(idespecie);
        idcategoria = Integer.valueOf(id_categoria);
        idhabitat = Integer.valueOf(id_habitat);
        nombre = String.valueOf(this.txtNombreEspecieMod.getText());

        especie.setIdespecie(idespecie);
        especie.setIdcategoria(idcategoria);
        especie.setIdhabitat(idhabitat);
        especie.setNombre(nombre);

     
        String mensaje = especieController.agregarEspecie(especie);
        JOptionPane.showMessageDialog(null, mensaje);
        listarEspecie();

       
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        EspecieDTO especie = new EspecieDTO();
        int idespecie = 0;
        int idcategoria = 0;
        int idhabitat = 0;
        String nombre = " ";

        String cadena1 = (String) cboIDhabitatMod.getSelectedItem();
        String[] partes1 = cadena1.split("-");
        String id_habitat = partes1[0];

        String cadena2 = (String) cboIDcategoriaMod.getSelectedItem();
        String[] partes2 = cadena2.split("-");
        String id_categoria = partes2[0];

        idespecie = Integer.valueOf(this.txtIdespecie.getText());
        idcategoria = Integer.valueOf(id_categoria);
        idhabitat = Integer.valueOf(id_habitat);
        nombre = String.valueOf(this.txtNombreEspecieMod.getText());

        especie.setIdespecie(idespecie);
        especie.setIdcategoria(idcategoria);
        especie.setIdhabitat(idhabitat);
        especie.setNombre(nombre);

        String mensaje = especieController.modificarEspecie(especie);
        JOptionPane.showMessageDialog(null, mensaje);
        listarEspecie();

       
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        int idespecie = 0;
        idespecie = Integer.parseInt(this.txtIdespecie.getText());
        String mensaje = especieController.eliminarEspecie(idespecie);
        JOptionPane.showMessageDialog(null, mensaje);
        listarEspecie();

       
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int idespecie = 0;
        //  idespecie = Integer.parseInt(this.txtIdespecie.getText());
        idespecie = Integer.parseInt(this.txtBuscarEspecie.getText());

   
        EspecieDTO esp = especieController.buscarEspecie(idespecie);

        if(esp.getIdespecie() != 0){
            this.txtIdespecie.setText(String.valueOf(esp.getIdespecie()));
            this.txtIdcategoria.setText(String.valueOf(esp.getIdcategoria()));
            this.txtIdhabitat.setText(String.valueOf(esp.getIdhabitat()));
            this.txtNombre.setText(String.valueOf(esp.getNombre()));
        }
        else{
            JOptionPane.showMessageDialog(null, "No existe la captura");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FrmPrincipal frm = new FrmPrincipal();
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cboIDhabitatModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboIDhabitatModActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cboIDhabitatModActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cboIDcategoriaMod;
    private javax.swing.JComboBox<String> cboIDhabitatMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbEspecie;
    private javax.swing.JTextField txtBuscarEspecie;
    private javax.swing.JTextField txtIdcategoria;
    private javax.swing.JTextField txtIdespecie;
    private javax.swing.JTextField txtIdhabitat;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEspecieMod;
    // End of variables declaration//GEN-END:variables
}
