/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer;

import ControllerLayer.MercadoController;
import dto.MercadoDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class FrmMercado extends javax.swing.JFrame {

    /**
     * Creates new form FrmMercado
     */
    
    private MercadoController mercadoController;
    
    public FrmMercado(MercadoController mercadoController) {
        initComponents();
        this.mercadoController = mercadoController;
        this.listarMercado();
    }
    
     public void listarMercado(){
        mercadoController.listarMercado(tbMercado);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        brnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdmercado = new javax.swing.JTextField();
        txtIdtipomercado = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMercado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        brnRegresar.setText("Regresar");
        brnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Mercados");

        jLabel2.setText("Id Mercado");

        jLabel3.setText("Id Tipo de Mercado");

        jLabel4.setText("Nombre");

        txtIdmercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdmercadoActionPerformed(evt);
            }
        });

        txtIdtipomercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdtipomercadoActionPerformed(evt);
            }
        });

        tbMercado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Mercado", "Id Tipo de Mercado", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbMercado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMercadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMercado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(brnRegresar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdmercado, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(txtIdtipomercado)
                                    .addComponent(txtNombre))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdmercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdtipomercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(brnRegresar))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int idmercado = 0;
        idmercado = Integer.parseInt(this.txtIdmercado.getText());

        MercadoDTO mer = mercadoController.buscarMercado(idmercado);

        if(mer.getMercado() != 0){
            this.txtIdmercado.setText(String.valueOf(mer.getMercado()));
            this.txtIdtipomercado.setText(String.valueOf(mer.getTipomercado()));
            this.txtNombre.setText(String.valueOf(mer.getNombremercado()));
        }
        else{
            JOptionPane.showMessageDialog(null, "No existe el mercado");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void brnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnRegresarActionPerformed
        FrmPrincipal frm = new FrmPrincipal();
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_brnRegresarActionPerformed

    private void txtIdmercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdmercadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdmercadoActionPerformed

    private void txtIdtipomercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdtipomercadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdtipomercadoActionPerformed

    private void tbMercadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMercadoMouseClicked
        int seleccion = tbMercado.rowAtPoint(evt.getPoint());
        try {
          
            System.out.println(Integer.parseInt((String)(tbMercado.getValueAt(seleccion, 0))));
            MercadoDTO mer = mercadoController.buscarMercado(Integer.parseInt((String)(tbMercado.getValueAt(seleccion, 0))));
            this.txtIdmercado.setText(String.valueOf(mer.getMercado()));
            this.txtIdtipomercado.setText(String.valueOf(mer.getTipomercado()));
            this.txtNombre.setText(String.valueOf(mer.getNombremercado()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO EXISTE EL MERCADO");
        }
    }//GEN-LAST:event_tbMercadoMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnRegresar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbMercado;
    private javax.swing.JTextField txtIdmercado;
    private javax.swing.JTextField txtIdtipomercado;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
