/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer;

import ControllerLayer.VentaController;
import dto.VentaDTO;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class FrmVenta extends javax.swing.JFrame {

    
     private  VentaController ventaController;
    
    public FrmVenta(VentaController ventaController) {
        initComponents();
        this.ventaController = ventaController;
        listarVenta();
    }
    
    public void listarVenta(){
        ventaController.listarVenta(tbVenta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        txtIdmercado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVenta = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtIdespecie = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        txtCantidadvendida = new javax.swing.JTextField();
        txtIdventa = new javax.swing.JTextField();
        txtNumerocaptura = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Id Venta");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Registro de Ventas");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel2.setText("RUC");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel3.setText("Id de Mercado");

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad Vendida");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel5.setText("Numero de Captura");

        tbVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Venta", "Numero de Captura", "RUC", "Id de Especie", "Id de Mercado", "Cantidad Vendida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbVentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbVenta);

        jLabel6.setText("Id de Especie");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        txtIdventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdventaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAgregar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnActualizar)
                                        .addGap(25, 25, 25))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNumerocaptura, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtIdventa, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(52, 52, 52)
                                .addComponent(btnBorrar)
                                .addGap(116, 116, 116)
                                .addComponent(btnBuscar)
                                .addGap(216, 216, 216))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtIdespecie, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtIdmercado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addGap(49, 49, 49)
                                                    .addComponent(txtCantidadvendida, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(btnRegresar)))))
                                .addGap(30, 30, 30))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(276, 276, 276)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdespecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdmercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumerocaptura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCantidadvendida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar)
                    .addComponent(btnBuscar)
                    .addComponent(btnRegresar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        VentaDTO venta = new VentaDTO();
        int numerocaptura = 0;
        long ruc = 0;
        int idespecie = 0;
        int idmercado = 0;
        float cantidadvendida = 0;

        numerocaptura = Integer.valueOf(this.txtNumerocaptura.getText());
        ruc = Long.valueOf(this.txtRuc.getText());
        idespecie = Integer.valueOf(this.txtIdespecie.getText());
        idmercado = Integer.valueOf(this.txtIdmercado.getText());
        cantidadvendida = Float.valueOf(this.txtCantidadvendida.getText());

        venta.setNumerocaptura(numerocaptura);
        venta.setRuc(ruc);
        venta.setIdespecie(idespecie);
        venta.setIdmercado(idmercado);
        venta.setCantidadvendida(cantidadvendida);

        String mensaje = ventaController.agregarVenta(venta);
        JOptionPane.showMessageDialog(null, mensaje);
        listarVenta();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        VentaDTO venta = new VentaDTO();
        int idventa = 0;
        int numerocaptura = 0;
        long ruc = 0;
        int idespecie = 0;
        int idmercado = 0;
        float cantidadvendida = 0;

        idventa = Integer.parseInt(this.txtIdventa.getText());
        numerocaptura = Integer.valueOf(this.txtNumerocaptura.getText());
        ruc = Long.valueOf(this.txtRuc.getText());
        idespecie = Integer.valueOf(this.txtIdespecie.getText());
        idmercado = Integer.valueOf(this.txtIdmercado.getText());
        cantidadvendida = Float.valueOf(this.txtCantidadvendida.getText());

        venta.setIdventa(idventa);
        venta.setNumerocaptura(numerocaptura);
        venta.setRuc(ruc);
        venta.setIdespecie(idespecie);
        venta.setIdmercado(idmercado);
        venta.setCantidadvendida(cantidadvendida);

        String mensaje = ventaController.modificarVenta(venta);
        JOptionPane.showMessageDialog(null, mensaje);
        listarVenta();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        VentaDTO venta = new VentaDTO();
        int idventa = 0;
        int numerocaptura = 0;
        long ruc = 0;
        int idespecie = 0;
        int idmercado = 0;
        float cantidadvendida = 0;

        idventa = Integer.parseInt(this.txtIdventa.getText());
        numerocaptura = Integer.valueOf(this.txtNumerocaptura.getText());
        ruc = Long.valueOf(this.txtRuc.getText());
        idespecie = Integer.valueOf(this.txtIdespecie.getText());
        idmercado = Integer.valueOf(this.txtIdmercado.getText());
        cantidadvendida = Float.valueOf(this.txtCantidadvendida.getText());

        venta.setIdventa(idventa);
        venta.setNumerocaptura(numerocaptura);
        venta.setRuc(ruc);
        venta.setIdespecie(idespecie);
        venta.setIdmercado(idmercado);
        venta.setCantidadvendida(cantidadvendida);

       
        String mensaje = ventaController.eliminarVenta(idventa);
        JOptionPane.showMessageDialog(null, mensaje);
        listarVenta();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int ncaptura = 0;
        ncaptura = Integer.parseInt(this.txtNumerocaptura.getText());

      
        VentaDTO ven = ventaController.buscarVentaPorNumeroCaptura(ncaptura);

        if(ven.getIdventa() != 0){
            this.txtIdventa.setText(String.valueOf(ven.getIdventa()));
            this.txtNumerocaptura.setText(String.valueOf(ven.getNumerocaptura()));
            this.txtRuc.setText(String.valueOf(ven.getRuc()));
            this.txtIdespecie.setText(String.valueOf(ven.getIdespecie()));
            this.txtIdmercado.setText(String.valueOf(ven.getIdmercado()));
            this.txtCantidadvendida.setText(String.valueOf(ven.getCantidadvendida()));
        }
        else{
            JOptionPane.showMessageDialog(null, "No existe la venta");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tbVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVentaMouseClicked
        int seleccion = tbVenta.rowAtPoint(evt.getPoint());
        try {
           
            System.out.println(Integer.parseInt((String)(tbVenta.getValueAt(seleccion, 0))));
            VentaDTO ve = ventaController.buscarVenta(Integer.parseInt((String)(tbVenta.getValueAt(seleccion, 0))));
            this.txtIdventa.setText(String.valueOf(ve.getIdventa()));
            this.txtNumerocaptura.setText(String.valueOf(ve.getNumerocaptura()));
            this.txtRuc.setText(String.valueOf(ve.getRuc()));
            this.txtIdespecie.setText(String.valueOf(ve.getIdespecie()));
            this.txtIdmercado.setText(String.valueOf(ve.getIdmercado()));
            this.txtCantidadvendida.setText(String.valueOf(ve.getCantidadvendida()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO EXISTE LA VENTA");
        }
    }//GEN-LAST:event_tbVentaMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FrmPrincipal frm = new FrmPrincipal();
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtIdventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdventaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbVenta;
    private javax.swing.JTextField txtCantidadvendida;
    private javax.swing.JTextField txtIdespecie;
    private javax.swing.JTextField txtIdmercado;
    private javax.swing.JTextField txtIdventa;
    private javax.swing.JTextField txtNumerocaptura;
    private javax.swing.JTextField txtRuc;
    // End of variables declaration//GEN-END:variables
}
